### PR TITLE
Styled select tag and replaced tabs with spaces.

### PR DESCRIPTION
**Pull request by KeizerDev**
screenshot from 2016-02-05 12-11-37

### CODE REVIEW

**Comment by zquestz** [comment]
NIce, going to look at this in a bunch of browsers later. Had some issues specifically with the select styling.

**Comment by zquestz** [comment]
Also tabs are appropriate as gofmt is used. Spaces are not gofmt friendly and will cause linters to complain.

**Comment by KeizerDev** [comment]
Ah, I did run `go fmt` on it was all fine. Exactly, sublime was the one who changed it.

**Comment by zquestz** [comment]
So I am definitely down to optimize the pull down if we can get it working perfect across all mobile and desktop browsers. You going to rebase this?

**Comment by zquestz** [comment]
Should we keep this open? We going to iterate on it?

**Comment by KeizerDev** [comment]
This was actually the only thing I've added
```css
select{position:absolute;top:1.5em;right:1.5em;background:transparent;width:9em;padding:0.3em 2em 0.3em 0.3em;font-size:16px;border:1px solid #ccc;height:2.5em;-webkit-appearance:none;-moz-appearance:none;appearance:none;background:url("data:image/svg+xml;utf8, <svg xmlns='http://www.w3.org/2000/svg' version='1.1' height='32px' width='32px'><text font-family='sans-serif' x='16' y='24' fill='darkslategray' font-size='20' text-anchor='middle'>[S]</text></svg>") 96% / 15% no-repeat #eee;}
option{text-align:left}
```

**Pull request closed without merging**
