### PR TITLE
Add nhaccuatui provider

### PR DESCRIPTION
**Pull request by NamPNQ**
Add nhaccuatui provider

### CODE REVIEW

**Comment by KeizerDev** [comment]
Please keep it to the format:
```
package gist

import (
	"fmt"
	"net/url"

	"github.com/zquestz/s/providers"
)

func init() {
	providers.AddProvider("gist", &GistProvider{})
}

// GistProvider adheres to the Provider interface.
type GistProvider struct {
}

// BuildURI generates a search URL for Gist.
func (p *GistProvider) BuildURI(q string) string {
	return fmt.Sprintf("https://gist.github.com/search?q=%s", url.QueryEscape(q))
}
```

So in your example it is `NhaccuatuiProvider`

**Comment by KeizerDev** [comment]
@NamPNQ Also, please rebase your commits to just a single one.

**Comment by KeizerDev** [comment]
@NamPNQ Please add it to the README.md too.

**Comment by NamPNQ** [comment]
@KeizerDev Done :D, tks you

**Comment by KeizerDev** [comment]
Great job! Thank you for contributing :smiley:

**Pull request merged**
