### PR TITLE
Fish completion

### PR DESCRIPTION
**Pull request by ajm188**
Adds support for provider completion for fish shell.

### CODE REVIEW

**Comment by KeizerDev** [comment]
Please squash your commits to just one

**Comment by ajm188** [comment]
@KeizerDev updated

**Comment by KeizerDev** [comment]
LGTM

**Comment by bucaran** [comment]
@KeizerDev @ajm188 Unless I am missing something, you don't need `__fish_s_needs_option_argument`. The following should accomplish the same:

```fish
function __fish_s_provider_list
    find $GOPATH/src/github.com/zquestz/s/providers -depth 1 -type d | sed 's:.*/::'
end

complete -f -c s -s p
complete -f -c s -n '__fish_s_needs_option_argument -p' -a '(__fish_s_provider_list)'

complete -c s -n "__fish_seen_subcommand_from -p" -a "(__fish_s_provider_list)"
```

**Comment by ajm188** [comment]
Is `__fish_seen_subcommand_from` a builtin?

**Comment by bucaran** [comment]
Try

```fish
type __fish_seen_subcommand_from
```

**Comment by ajm188** [comment]
Ok, cool. But let's say I did `s -p amazon blah blah<TAB>`, that would trigger the autocomplete, which is wrong. Right?

**Comment by bucaran** [comment]
I don't know how `s` works, but why would that be wrong? I am trying your code, hold one a sec :smile:

**Comment by ajm188** [comment]
(It's in the docs): s supports searching by providers, so I can say `s -p amazon <search>`, to search amazon directly. The autocompletion is just for the providers. So, if I use `__fish_seen_subcommand_from`, it's checking that I used `-p` at all, where my code is checking that I'm currently in the process of typing the argument to `-p`.

**Comment by bucaran** [comment]
s

Is this how `s` is supposed to behave?

**Comment by bucaran** [comment]
And this is the effect using what I was suggesting.

s

**Comment by ajm188** [comment]
Both of those actually look wrong to me. I don't think you can use two providers simultaneously. That wouldn't make sense.

**Comment by ajm188** [comment]
The code I was _trying_ to write was something to the effect of "if -p is the last thing you typed, or if you are typing the word immediately after -p, then we should do completion"

**Comment by bucaran** [comment]
@ajm188 Alright, let me see, hold on another sec.

**Comment by bucaran** [comment]
Is that closer?

s

**Comment by ajm188** [comment]
I can't tell if it's completing the "x" multiple times, and also I would say the "-p" shouldn't be able to appear twice.

**Comment by bucaran** [comment]
I don't think you can't prevent short options like `-p` from appearing multiple times, because a utility could have more than one short option and they are often joinable.

Like, say, `npm`:

s

**Comment by bucaran** [comment]
Edited my comment above. Cheers!

**Comment by ajm188** [comment]
Hmm, I think I need to think about this some more. Everything seems wrong to me.
Thanks for the input!

**Comment by bucaran** [comment]
@ajm188 Ha! Please let me know if you figure out exactly what you needed or whatever you come up as I am interested too. Ping me or send me an email to the address listed on my profile page.

:+1:

**Comment by zquestz** [comment]
I made minor adjustments in master already. However I am happy to take a revision PR. I don't use fish so I didn't test it super extensively. zsh user here.

**Pull request merged**
