### PR TITLE
Added zhihu provider

### PR DESCRIPTION
**Pull request by knarfeh**

### CODE REVIEW

**Comment by zquestz** [comment]
Thanks for the PR, if you can change the Tag method, then I am happy to merge it. =)

**Comment by knarfeh** [comment]
How to amend it? zhihu is the Chinese version of quora, they are all types of forums.

**Comment by knarfeh** [comment]
Missing a full stop?

**Comment by zquestz** [comment]
I will go ahead and merge as is, then amend. Thanks again!

**Comment by knarfeh** [comment]
Thank you! 😬

**Pull request merged**
